language: java
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: script
  script: mvn deploy -s .travis.settings.xml
  skip_cleanup: true
env:
  global:
  - secure: PtiiISyay9VW4p8ta7OUD40ntQXVaZEBfbn3+u17KNZsvp8e0F1NCVT4muWC9CSl/D3RPzqVR8JMfuqzLu4q6gVsb+vIXFqyx0P+LstWyBGW64i072GDkj2jAJeUi056b3TKmsY0DZbX//rF76n9xOY/wuuwLwoYxZPVRwtbULP5IkJVbnTGwBkliygFLv03zSx6iRHrI4WxjfKDFHW+IVYr72u4E8oOs9FCGNraLI0cJFgyGRZd45NVVqLuU9fdbmVoq/ClKH8rUmh76G9e+hoY4UXzaOBjKpZzNZ7TqG4xV/k53gHNvP2E6ZCzol1jBjsmmsA4p7R7s2L10SFB61nuqnQmFydedUFGuwaJeh4xW46QmVq39NM8OQdLfPury0EuOXco8b3maBJgVk1AKVtUHb3fa3uC3lP5cduF9rQXFR7LWN8fUlUaq6SkpmRDZYnst7CfoopXrJ+eT+qEEOt7BARY23sGDy//6XgqedJdhIzUuwtpdRMQhO3vu4uMaHZDN0kzt5RPS42EB7f4K5rJ7dOrQAHy0NykE3X/8weh1tZGqiVfeTZNGdFdAP1c6nbORNhD9v5yWLPPLNrumwXCPYecloe/jfTvAJUDgt7IJuK83eEwjtGNx2uzd+sn1ECyWJ2b9g+PST8mam8nVh60SNUgwnR/Mg9M7OPqrxo=
  - secure: GAAJtH9LOAmEMyRQzamt9cEU+5fvuDlRkkhLxktNLmY6LwVgxF8qZJWN2KwwahumMH19iJ18+VHtEe1g+AJLMceM+9nXuEwTY9W1GyD5j1umjaXOaZKXQH1eKHDDr5g0MK5CSFIzI+PWOMomy7+nWx567c1Fdk9HWD9mK2fZIQfT6WJD9Oy5fpIF+XgKrAtBCC5eAK5gaL9DSO5rMZNn3Tf0RwKn6gBuwntH6yClPg984rIqiZekaMw9G+X1sZpO7yNHMTSGaFEQIJ9b4w5wrYFd19Rp4ge7eQ5CVDABiUTvQ3tsh8mfLM1ODqOvfNY1y4cRg9owPoep4gt4JbJxeVqp9jBRqla/zeFDcLbty7359po5uXFi9F/o+68I3YDooKdhq9iiBpuwj49rrYQyPKV1ZM4h8Ms7vmhbptKQwLn/LDrQ0erDwU6nOkZEeM+oOm1pGqk6Sa8vsfsmPLSo1hT7jRf5039BAKbff2AmFcoNUHauzgfp87q+/m4UMJyVYAnu05JUc42ZQBG0MPtTIqEezu0Yv8YTyw3tkHN1qwJEmB+9C/VtJc6PnIsF7GtHWS9zQ56WiHaAfktIqGffMW+Y5nLJeG3XPNwzse7b1P5raHwBk5h8Y8KvRkZtD6qab7WTyTcXLPx+ChNPAeFbBtTvGceznwRzhja1PMImbtk=
