language: java
jdk:
  - oraclejdk11
branches:
  only:
    - master
    - develop
dist: trusty
install: true
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=API4KBs_kmdp-models -Ppublic -q
deploy:
  - provider: script
    script: mvn deploy -Ppublic -s .travis.settings.xml
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: mvn deploy -Ppublic -s .travis.settings.xml
    on:
      branch: develop

addons:
  sonarcloud:
    organization: "api4kbs"
    token:
      secure: "SVui6K5RW1mT5HyCOa8XrLH6Nf4DabE74dPTYx4eJGS4Yf5vtjaC0ZRBtkUwwJTv2nBbgQpswOcaKWFWgUXn3Wg0cgR+5Y0ZPQjMgdOB8IAos/JmtcdhSNDXduyo4+FB00isDVG1oDGA1TVSv4wRySu4wcl2ytcPgNVQZtBLJreqk/mEu2vmgEn0RsS27ESf8KSJ4dAQHKYOZvxdL+1l8bfPU27RX2BS4kFopRTGjG2hGkqcI+zAlCLWtxQlw1Xj0PBZjbri4LFRT9k9TNcn+oVBcpIZd+3802+QN+1nEyuK8jY3nBv1aMOMNj1qEghEsjOJ5PtiIZaB9VAEGqHivXzlTVeCLLIOmFipOQ0XBpDzY4W8JJm9zMMXXc4pnEOCGKSRcSWGyEvc9TW8FDOEeRtbJUIyiHhD8ocIRi8P3Uj4xJzAmOeL6hkyI+p5CDzY1WV+Wdith7qjPHy7XrDtjCmUk6IzqbeFfTyCAfwiKoEP7wMhpXi7qppUAZ6t2v8K9Np6tSF3aLp2PeHO6CR47KxxUe2Pf5S0B26oHGzolydPBifvZqwX+63PcpPB0H3eTliQtoRWPDt7cuLI18g0sCcL+VxP0pmUoZkiLdFWiY2w5843g4FdTZzH06uym6fx6h/V8o/HQKD9R2y3bDAtEDs0elbgwBNd8NYIXqDAH+w="

env:
  global:
  - secure: PtiiISyay9VW4p8ta7OUD40ntQXVaZEBfbn3+u17KNZsvp8e0F1NCVT4muWC9CSl/D3RPzqVR8JMfuqzLu4q6gVsb+vIXFqyx0P+LstWyBGW64i072GDkj2jAJeUi056b3TKmsY0DZbX//rF76n9xOY/wuuwLwoYxZPVRwtbULP5IkJVbnTGwBkliygFLv03zSx6iRHrI4WxjfKDFHW+IVYr72u4E8oOs9FCGNraLI0cJFgyGRZd45NVVqLuU9fdbmVoq/ClKH8rUmh76G9e+hoY4UXzaOBjKpZzNZ7TqG4xV/k53gHNvP2E6ZCzol1jBjsmmsA4p7R7s2L10SFB61nuqnQmFydedUFGuwaJeh4xW46QmVq39NM8OQdLfPury0EuOXco8b3maBJgVk1AKVtUHb3fa3uC3lP5cduF9rQXFR7LWN8fUlUaq6SkpmRDZYnst7CfoopXrJ+eT+qEEOt7BARY23sGDy//6XgqedJdhIzUuwtpdRMQhO3vu4uMaHZDN0kzt5RPS42EB7f4K5rJ7dOrQAHy0NykE3X/8weh1tZGqiVfeTZNGdFdAP1c6nbORNhD9v5yWLPPLNrumwXCPYecloe/jfTvAJUDgt7IJuK83eEwjtGNx2uzd+sn1ECyWJ2b9g+PST8mam8nVh60SNUgwnR/Mg9M7OPqrxo=
  - secure: GAAJtH9LOAmEMyRQzamt9cEU+5fvuDlRkkhLxktNLmY6LwVgxF8qZJWN2KwwahumMH19iJ18+VHtEe1g+AJLMceM+9nXuEwTY9W1GyD5j1umjaXOaZKXQH1eKHDDr5g0MK5CSFIzI+PWOMomy7+nWx567c1Fdk9HWD9mK2fZIQfT6WJD9Oy5fpIF+XgKrAtBCC5eAK5gaL9DSO5rMZNn3Tf0RwKn6gBuwntH6yClPg984rIqiZekaMw9G+X1sZpO7yNHMTSGaFEQIJ9b4w5wrYFd19Rp4ge7eQ5CVDABiUTvQ3tsh8mfLM1ODqOvfNY1y4cRg9owPoep4gt4JbJxeVqp9jBRqla/zeFDcLbty7359po5uXFi9F/o+68I3YDooKdhq9iiBpuwj49rrYQyPKV1ZM4h8Ms7vmhbptKQwLn/LDrQ0erDwU6nOkZEeM+oOm1pGqk6Sa8vsfsmPLSo1hT7jRf5039BAKbff2AmFcoNUHauzgfp87q+/m4UMJyVYAnu05JUc42ZQBG0MPtTIqEezu0Yv8YTyw3tkHN1qwJEmB+9C/VtJc6PnIsF7GtHWS9zQ56WiHaAfktIqGffMW+Y5nLJeG3XPNwzse7b1P5raHwBk5h8Y8KvRkZtD6qab7WTyTcXLPx+ChNPAeFbBtTvGceznwRzhja1PMImbtk=
  - secure: hVXi37UwNeDW7wB6Y+Dzyq72+RV2G1iupVHxLtL99qHjHpsjIHwGWxjzSNYq1GSiJ1b1DMiCEyi6T/8nBiaa2Rwc3xOkXzO/q5Ab53DYfQd+Aia1OVkc1RG5zx/Q5NnMmv12Yu5wCwuqvGMdwE3JVOphBEAztXRVkmn5T/YZBVOlhyW06AJ/ZeQSuT4p+Yuja3g3iuA4Ssh/fchGDWRv5EraBuZWhMqMqlKi77WKrPAWAT8tFL87KRVdcQKXNjShexlLcbwOa5BM6qnZPYQGdhzae9yDBQ8mTQq6kgbDDs9feTB59AIhSkl/UpiBWdzvHh5bMBXRGyuEEMglIjCyU8OfQHx6ush86HLTUh8i/Iy1Nzd2qnPVsZCMZOv9nM4lhPBh7J0YGDYaEABe8eG+g1DyP3AYclNBmcN801u0suJWbRtupjRJJuSW7w88gCYksdj35a/b892CT1B/tLGQmzhV4lbHfTxE8bk2iLjHj7znbjw2Z7/mYtUsV3fWOHciVtkZn5ZJzdEfcSaHqCkI4ma2prBLTzn7QKz94Womu5Km0sSQ4W4ball1FOjVes9LqHrrRAgjm6mO1lr3i0d657HXaauEnqxi5d7irsIJ8xSV7ytqLOGxovj+Ko5mIKmYZh0qT9knbZO1Bl1rJqwOSEfvKuqDhmKPYb7VkGlVq08=
