PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?X
WHERE {

    OPTIONAL {

        ?X a owl:NamedIndividual;
           rdf:type ?type.
        ?type rdfs:subClassOf* ?focus.

        FILTER isUri( ?X ).

    }

}




