PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX know: <https://www.omg.org/spec/API4KP/api4kp/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX w3c: <http://www.w3.org/TR/>
PREFIX dol: <http://www.omg.org/spec/DOL/DOL-terms/>

SELECT ?L ?P ?NS ?Code ?Ver
WHERE {
  {
    ?L a know:ConstructedLanguage;
      dc:identifier ?Code;
      dol:supportsSerialization ?NS.

    OPTIONAL { ?L owl:versionInfo ?Ver. }
    BIND( CONCAT( ?Code,
                  IF( BOUND(?Ver), CONCAT( "-", ?Ver ), "" )
    ) as ?P)

    ?NS know:depends-on ?MF.

    ?MF dc:source "http://www.w3.org/TR/xml11".
  }
  UNION
  {
      ?NS a know:Lexicon;
        dc:identifier ?P.
  }
}