PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX know: <http://www.omg.org/spec/API4KP/core#>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX w3c: <http://www.w3.org/TR/>
PREFIX dol: <http://www.omg.org/spec/DOL/DOL-terms/>

SELECT ?L ?P ?NS
WHERE {
  {
       ?L a know:ConstructedLanguage;
            dol:supportsSerialization ?Ser.

        ?Ser dc:source ?NS;
            know:associated-to w3c:xml11.
  }
}